// 
// ..DO NOT EDIT THIS FILE. It's created automatically from Xcode
// Last update: Wed Aug 26 18:10:40 CVT 2015
// 
// 
// INTRODUCTION
// ============
// How to mix XCode version numbers + GIT 'commit' and 'tag' numbers
// in order to have a program version string that is useful and
// at the same time is compatible with AppStore and GIT.
// 
// Objective: Create a set of #define's in an include file that will be
// consumed from your project in order to show the version
// 
// 
// XCode has created this file with the #define's below and has also
// changed the following attributes in the plist file:

// /Users/luis/priv/prog.git/github/lupa/lupa/Info.plist
//    XCode Version = CFBundleShortVersionString = @"0.0.9"
//    XCode Build   = CFBundleVersion            = 32

// 
// Defines created by XCode that can be used in this project: 
// 
let skPROGRAM_DISPLAY_VERSION = "0.0.9"
let ikPROGRAM_VERSION         = 32
let skPROGRAM_BUILD           = "7f2f932"
