// 
// ..DO NOT EDIT THIS FILE. It's created automatically from Xcode
// Last update: Thu Sep 17 20:17:38 CEST 2015
// 
// 
// INTRODUCTION
// ============
// How to mix XCode version numbers + GIT 'commit' and 'tag' numbers
// in order to have a program version string that is useful and
// at the same time is compatible with AppStore and GIT.
// 
// Objective: Create a set of #define's in an include file that will be
// consumed from your project in order to show the version
// 
// 
// XCode has created this file with the #define's below and has also
// changed the following attributes in the plist file:

// /Users/luis/priv/prog.git/github/lupa/lupa/Info.plist
//    XCode Version = CFBundleShortVersionString = @"1.0.0"
//    XCode Build   = CFBundleVersion            = 46

// 
// Defines created by XCode that can be used in this project: 
// 
let skPROGRAM_DISPLAY_VERSION = "1.0.0"
let ikPROGRAM_VERSION         = 46
let skPROGRAM_BUILD           = "1c9b9b4"
